AWSTemplateFormatVersion: '2010-09-09'
Description: S3 + CloudFront + Route53 for uk-student-loan-hell

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: uk-student-loan-hell
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub ${S3Bucket.Arn}/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}

  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: uk-student-loan-hell-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - jeevancyriac.com
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt S3Bucket.RegionalDomainName
            OriginPath: ''
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !Ref OriginAccessControl
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # CachingOptimized
          Compress: true
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /uk-student-loan-hell/index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /uk-student-loan-hell/index.html
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:515708633777:certificate/37a8b4ca-165d-4a87-86b7-a129846cd616
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        HttpVersion: http2and3
        PriceClass: PriceClass_100

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z067310534WI2X3D9QMGK
      Name: jeevancyriac.com
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  BucketName:
    Value: !Ref S3Bucket
  CloudFrontDistributionId:
    Value: !Ref CloudFrontDistribution
  WebsiteURL:
    Value: https://jeevancyriac.com/uk-student-loan-hell
